### ISSUE TITLE
[ObjectTable] "BardToolbox" is accessing "ObjectTable" outside the main thread. This is deprecated.

### ISSUE THREAD

**Issue by burningyeti** [BardToolbox/BardToolbox-Release#3]
**Describe the bug**
It seems a feature that was previously utilized for this plugin has been deprecated. If I leave BardToolBox on for any length of time, it will eventually conflict with other plugins and cause the game to crash.

**To Reproduce**
1. Enable mbard and BardToolBox only, disabling all other plugins for testing.
2. Load into a population-less or dense area (I've determined that this gives enough variance to determine it's not an issue with low or high settings.
3. With the Dalamud console live, you will consistently see the error:
[ObjectTable] "BardToolbox" is accessing "ObjectTable" outside the main thread. This is deprecated.

**Expected behavior**
I'm not entirely certain what feature within the tool may be causing this error, but this is the only plugin that I've encountered that throws up a warning, then makes the game crash.

**Screenshots**
![Bardtoolboxerror](https://github.com/user-attachments/assets/366e1b86-e60e-44da-937e-1b5b35be4451)

**Plugin Version:**
 - Version 2.1.0.0

**Comment by BardToolbox** [comment]
Thanks for letting us know. This is related to syncing client stats so it shouldn't be causing the crash. We've got it fixed in the new update. Let us know if there's any further issues.
